width: 40
height: 80
i: 570 
j: 620
states: 
   default: 
      - owl.jpg
   default_up: 
      - owl.jpg
   default_right: 
      - owl.jpg
   default_left: 
      - owl-flip.jpg
   up: 
      - owl.jpg
      - owl-flip.jpg
   down: 
      - owl.jpg
      - owl-flip.jpg
   left: 
      - owl.jpg
      - owl-flip.jpg
   right: 
      - owl.jpg
      - owl-flip.jpg
