language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install build-essential checkinstall && sudo apt-get build-dep imagemagick -y
# command to run tests
script: 
  - ./lint.sh
  - ./thing.py
