width: 40
height: 80
i: 10 
j: 17
states:
   default:
      - test.png
   default_up:
      - test.png
   up:
      - test.png
   down:
      - test.png
   left:
      - test.png
   right:
      - test.png
