width: 40
height: 80
i: 150 
j: 10
states:
   default:
      - test.png
   default_up:
      - test.png
   default_right:
      - test.png
   default_left:
      - test.png
   up:
      - test.png
   down:
      - test.png
   left:
      - test.png
   right:
      - test.png
