width: 50
height: 50
i: 120 
j: 120
states:
   default:
      - test.png
   default_up:
      - test.png
   up:
      - test.png
   down:
      - test.png
   left:
      - test.png
   right:
      - test.png
